language: python
python:
- '3.6'
env:
  global:
  - DOCKER_USERNAME=ctmanjak
  # DOCKER_PASSWORD=
  - secure: VprSO3nHfVAqeOTFjC6i3p89azJ//+CYMo08ptfbgT6wQA6NtE3JOXHJnUbo0Dxq8Bd/4cIh/DBeeiSu5EkEYF66Bf2k95ayjYI2MAcMSSAW3KnEnzVCwtL4CwLTEOxyCyKbj4ujAbdd6sL+LdNkhwPZ6Dw5CnqABaUCl3dY5l+XOff0NEZhRllEwlVeyqvhwz5Gc4x8gg8GPkW3kdvevA9EALDCgthzHYkktDPQCC5kQWIyWYnIq9/3CPZj4yG25/HEGVa7+OUtyYiBe6hlIBJY4pnc2z0JOVzhin7y72mB0kYVGp+NIv2d8GyraxcZlLt+n74R70kvcEzBSRhQppjonwzuovSlAq+KYNH3cTtK4FXPK6kYVrGPxSbuOnid/wU6TgA2zlxdz1DTqpI4TYs4YieYA0QDb8yPL4zOFJe5/0OelBiKrWTs2T0yx/7VSR9MrH1DiMUqDCgqC3vfz+FSj3GzqeFr1QGQTWEoMB+lHliEwObeGzp8hvyVTSOOtlVkzKlqv+YZMP5j5yIKUOPCL2++AVABnLzj/7tvS5MQAEZqXrXvGyZXWCt9r3ldQoqF2GYhkE5o1oNgXR2hJ1I2Px9A3n/OSosPl0ebS+IVwQpbysq2HNBs7SPuh/RHcSD6oJif3AAN1ePIN8EqTzBtr1aS1EKB16XlDZs7iGc=
  # TARGET_IP=
  - secure: KmN+Lf9MXt0gdeVnWVbpMtvJMk99SS5r/KvXi3b0yvDiqh8FiP7HGi1x1hf1ogZkA7kI5oZuckX/8F7TXHxDiMsx+PkUHeouct39IyZetynQEGRjScaQTLkvuHZs/jFmWhPQdjCEYYJoCTvtV/9JBUzghK2UqEGuKK50HQQykhEyJdwlASCpDuVXXwkarNz5XQNHd89mbwNhpSfoPxQgtSuaEb3kzrrrH6XQr4qP7tWQL0guxFB5KPFhDhuzZxkZShtX3D92fdO5yMcyZ01dYdei8EkYY6lWUdcPyLXybisGzZgIUIUC8wtSWbPz0kCHN57kTatsCbOXWP6AzQKXXFUiBU+AXP4GSYx2q01cpJb6HmVTXxdBtapxSWQVYCNqNFSu+WEAFrKAyNkA4lFP9uFPnhTEWrs7tyFUxzSAqsdHkT0uZboD74o21/PgLi1DDBDXC/5HveTA/cbqL/2YRCtdWXYc3cWvCD976Cj6ub25AiloSBQeh6/dKb/FeflC6C/6XRIVIitNzjdBW85SwjtpX6i2gQbIllgFGgimZ8HzpDteu8PPpt2FqTSVUka4UinR6Sj/xIZp4BWx8BDYh+9bkVyEJNo1nPQ1lezL6y2x9Pu55EnwOB2SRT9Z9YIz0YYiL4274FWk8REgKUtbsS7cwWd3w8X7J7uvOTlOXqQ=
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_3b9f0b9d36d1_key -iv $encrypted_3b9f0b9d36d1_iv -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
install:
- pip install -r requirements.txt
script:
- bash image_build.sh
deploy:
  skip_cleanup: true
  provider: script
  script: bash docker-deploy.sh $TARGET_IP
  on:
    branch: master
notifications:
  email:
  - ctmanjak@gmail.com
  slack:
    secure: IYmND+OxQ+uHEKip0BKlVM+CEe7Yi+r3DYi3/c6zDzPsS3BPUkJ8nz0x//BvcMbnCr8ODrDJircH8RfrHmJmxHbPnpFtOmEBpUXMsCqd7sETiZBdsll9HTGbpRHzG/8N/VQcz5RTGUj5BlPt31TzxBIKqSOnNe9pH03CfMgRIPITyUVcBUJf6jk7axXf68UWclnT0LvvPPgdtQX3vlURwVibAGh8NLjWVWRNVPMMepaWhAb9NXGBk6j1wNKb8nzdJJqvvih0Bv37gJF2kvuYojFvkhWtv3Ga+IgTGi5jQkzJGWdtmjAETcOLbyPUn3IBcagswMRJVfU3AinYmOrBltgIqYdp3fBiA5eZPYbsT9G7bX8L3mH39RNuU2ruZrr5EZaL1e1bsa6IfmZY9TmofTyOrtBrrAPqb1lT+Q7jlrjiRL0yVOPfprBRCSRkHLl5mMlL8ky/TY6eFEuye478wtThcecZePV7Ga4Y1qveLWpR6gscH7jLzN+yM7rqjALVPe6aw3a2aFLTIbl7HINtsbXvyaLfElnFoE061X+d94xbHBPDJ3900nmSXpeERKkcPzSdlYB7VKiGaMN0rxKB/HH3h7xNzp4GYlzUVCzBETL1L6tGrsoYzgaOxxdaA9WP/6tq2CcvSIklSlvZmdqUrDR4zTHF9kW7MFSVdERH4TQ=
