language: python
python:
- '3.6'
env:
  global:
  - DOCKER_USERNAME=ctmanjak
  # DOCKER_PASSWORD=
  - secure: VprSO3nHfVAqeOTFjC6i3p89azJ//+CYMo08ptfbgT6wQA6NtE3JOXHJnUbo0Dxq8Bd/4cIh/DBeeiSu5EkEYF66Bf2k95ayjYI2MAcMSSAW3KnEnzVCwtL4CwLTEOxyCyKbj4ujAbdd6sL+LdNkhwPZ6Dw5CnqABaUCl3dY5l+XOff0NEZhRllEwlVeyqvhwz5Gc4x8gg8GPkW3kdvevA9EALDCgthzHYkktDPQCC5kQWIyWYnIq9/3CPZj4yG25/HEGVa7+OUtyYiBe6hlIBJY4pnc2z0JOVzhin7y72mB0kYVGp+NIv2d8GyraxcZlLt+n74R70kvcEzBSRhQppjonwzuovSlAq+KYNH3cTtK4FXPK6kYVrGPxSbuOnid/wU6TgA2zlxdz1DTqpI4TYs4YieYA0QDb8yPL4zOFJe5/0OelBiKrWTs2T0yx/7VSR9MrH1DiMUqDCgqC3vfz+FSj3GzqeFr1QGQTWEoMB+lHliEwObeGzp8hvyVTSOOtlVkzKlqv+YZMP5j5yIKUOPCL2++AVABnLzj/7tvS5MQAEZqXrXvGyZXWCt9r3ldQoqF2GYhkE5o1oNgXR2hJ1I2Px9A3n/OSosPl0ebS+IVwQpbysq2HNBs7SPuh/RHcSD6oJif3AAN1ePIN8EqTzBtr1aS1EKB16XlDZs7iGc=
services:
- docker
install:
- pip install -r requirements.txt
script:
- bash image_build.sh
notifications:
  email:
  - ctmanjak@gmail.com
  slack:
    secure: L06LWIJkZk9v+m3ouCdhF5RbpJtWW/+AtxBKmlxzGo5SUn9XK59YHfb1srN3y/N9mU9cwBXJiCEUovZYWH8s8ArwBJnB7KjLWvTNOy1naGZivH09aMNgzfJQJ8Ujr4qSP3SvB7tdYX5VY0c7zvf1UvB05QyUJ37gdbglcudzdbBfNI3i3mQAyW2Yo1JWyWYPib0jDUzTLRJfGAc7MO1B1yG23yk2f/mHd4O/YyvW+nDKGktRvp2gK+PPh6FhjWfCIts28/ZRLRYnWZ/aoMQvv4NU0yrHPvG14UGStCe8SHjoy61stRwF0712Z1SgNq+ImpWBzm0EY7KAfuOe5krw+0UzUJS5+svAoUuYoeWCntBYz+8ia1VpQ6BUAlMVA7qIwdR382Tk4tO0RXYsSOXScOEMnHm52lkEl79r6jOR0mo9FlK9iRHmb8SE5f+hW5BvxwofgGq5yyErTf+Q1E3XT5gJeJ1uNg7iX2jGJGQiafaV6qVIKQ7pfyRjFyTLGCtPXtGRnK9PRuj6ODFxb1dKGW99Fu9MXSKtcPBJ+q0bmZZJo+Nheu6mfYBqAPsvPa5NqZeu8SetfsBR+j1ZyErz3/zQKcREXHhRu/9jtc9O9nSxc1RhFH3JcShcDbN51OJC6HaJ/yBO9Fs8ZjzE9ataGRd+VAD2lW+/oVDtnuozjeQ=
